### ISSUE TITLE
Getting info of a factoid with unicode characters causes an exception

### ISSUE THREAD

**Issue by gunnbr** [gunnbr/gthx#49]
For an example, use

    info zalgo

Which causes:
```
2018-01-04 20:33:09+0000 [Gthx,client] info request for 'zalgo' 
2018-01-04 20:33:09+0000 [Gthx,client] Factoid 'zalgo' has been referenced 7 times
2018-01-04 20:33:09+0000 [Gthx,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 221, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 2430, in dataReceived
            basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
          File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/usr/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 2438, in lineReceived
            self.handleCommand(command, prefix, params)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 2482, in handleCommand
            method(prefix, params)
          File "/usr/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 1939, in irc_PRIVMSG
            self.privmsg(user, channel, message)
          File "/usr/sbin/gthx/gthx.py", line 556, in privmsg
            print "At %s, %s set to: %s" % (factoid[4], user, safeValue)
          File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 500, in write
            data = data.encode(self.encoding)
        exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 46-51: ordinal not in range(128)
```

**Comment by gunnbr** [comment]
Forgot to close this in the commit comment:
Removed unnecessary utf-8 decoding of the log for info requests as it was causing an exception under some circumstances. The exact circumstances are unclear though, since running the exact same code from the same directory on the exact same machine but with a different IRC user was not able to reproduce it.
